// English-only copy for the private admin workspace. Independent of app locale.
const adminCopy = {
    "admin.signedInAs": "Signed in as {email}.",
    "admin.controlRoom": "Control room",
    "admin.hostOrchestrator": "Host orchestrator",
    "admin.hostNotConfigured": "Add `HOST_ADMIN_BASE_URL` and `HOST_ADMIN_TOKEN` in your env vars to unlock the full AI host console.",
    "admin.hostConfigured": "Available tools load automatically when you open the workspace.",
    "admin.loadingCapabilities": "Loading admin capabilities...",
    "admin.loadCapabilitiesError": "Unable to load host admin capabilities.",
    "admin.refreshJobError": "Unable to refresh host job status.",
    "admin.loadedCapabilities": "Loaded {stations} stations, {archetypes} archetypes, and {operations} operations.",
    "admin.station": "Station",
    "admin.forceArchetype": "Force Archetype",
    "admin.noArchetypes": "No archetypes are available from the host service.",
    "admin.archetype": "Archetype",
    "admin.selectArchetype": "Select archetype",
    "admin.dryRun": "Dry run",
    "admin.trackFocus": "Track focus",
    "admin.trackFocusDescription": "Optional. Leave it unset to let the server pick the focus automatically.",
    "admin.useServerDefault": "Use server default",
    "admin.runForceArchetype": "Run Force Archetype",
    "admin.selectStationAndArchetypeHint": "Select a station and archetype to continue.",
    "admin.jobRunning": "Job Running...",
    "admin.forceArchetypeAccepted": "Force archetype request accepted.",
    "admin.forceArchetypeError": "Unable to start a forced host run.",
    "admin.scheduleGenerator": "Schedule Generator",
    "admin.scheduleGeneratorDescription": "Run the schedule generator for the selected station.",
    "admin.scheduleGeneratorAccepted": "Schedule generator request accepted.",
    "admin.scheduleGeneratorError": "Unable to start the schedule generator.",
    "admin.forceApply": "Force apply",
    "admin.seedMode": "Seed mode",
    "admin.seedModeDescription": "Use stable mode for deterministic weekly plans, fresh for a reroll, or custom to reproduce a manual variation.",
    "admin.customSeedKey": "Custom seed key",
    "admin.enterCustomSeed": "Enter a custom seed key first.",
    "admin.weekStartDate": "Week start date (YYYY-MM-DD)",
    "admin.tuning": "Tuning",
    "admin.tuningDescription": "Leave fields blank to use the server defaults.",
    "admin.openRatioMin": "Open ratio min",
    "admin.openRatioMax": "Open ratio max",
    "admin.minOpenSlots": "Min open slots",
    "admin.maxOpenSlots": "Max open slots",
    "admin.minBlockMinutes": "Min block minutes",
    "admin.maxBlockMinutes": "Max block minutes",
    "admin.invalidNumber": "{label} must be a valid number.",
    "admin.invalidInteger": "{label} must be a whole number.",
    "admin.runScheduleGenerator": "Run Schedule Generator",
    "admin.selectStationHint": "Select a station to continue.",
    "admin.forceApplyDisabledHint": "Turn off Dry run to enable Force apply.",
    "admin.latestHostJob": "Latest Host Job",
    "admin.polling": "Polling...",
    "admin.archetypeLine": "Archetype: {value}",
    "admin.focusLine": "Focus: {value}",
    "admin.modeDryRun": "Mode: Dry run",
    "admin.forceApplyEnabled": "Force apply enabled",
    "admin.seedModeLine": "Seed mode: {value}",
    "admin.customSeedLine": "Custom seed: {value}",
    "admin.seedSaltLine": "Seed salt: {value}",
    "admin.weekStartLine": "Week start: {value}",
    "admin.openRatioMinLine": "Open ratio min: {value}",
    "admin.openRatioMaxLine": "Open ratio max: {value}",
    "admin.minOpenSlotsLine": "Min open slots: {value}",
    "admin.maxOpenSlotsLine": "Max open slots: {value}",
    "admin.minBlockMinutesLine": "Min block minutes: {value}",
    "admin.maxBlockMinutesLine": "Max block minutes: {value}",
    "admin.exitCodeLine": "Exit code: {value}",
    "admin.acceptedAtLine": "Accepted: {value}",
    "admin.startedAtLine": "Started: {value}",
    "admin.finishedAtLine": "Finished: {value}",
    "admin.jobCompleted": "{operation} completed for {station}.",
    "admin.jobFailed": "{operation} failed for {station}{suffix}.",
    "admin.focusCurrent": "Current track",
    "admin.focusNext": "Next track",
    "admin.seedStableWeek": "Stable week",
    "admin.seedFresh": "Fresh",
    "admin.seedCustom": "Custom",
    "admin.statusAccepted": "Accepted",
    "admin.statusRunning": "Running",
    "admin.statusSucceeded": "Succeeded",
    "admin.statusFailed": "Failed",
    "admin.englishTestStream": "NeuralCast (EN) test stream",
    "admin.englishTestStreamDescription": "Private shortcut for monitoring the English host rollout.",
    "admin.playEnglishTest": "Play test stream",
    "admin.stopEnglishTest": "Stop test stream",
    "admin.openPublicPage": "Open public page",
    "admin.testStreamError": "The English test stream could not be played.",
    "common.submitting": "Submitting...",
    "nav.backToRadio": "Back to radio",
} as const;

export function adminText(key: keyof typeof adminCopy, params?: Record<string, string | number>): string {
  return Object.entries(params ?? {}).reduce<string>((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), adminCopy[key]);
}
